#################################################################################################
### This requests use REST Client                                                             ###
### Install Componente: https://marketplace.visualstudio.com/items?itemName=humao.rest-client ###
#################################################################################################

### Get Report

GET http://localhost:3000/analytics HTTP/1.1
content-type: application/json

{}

### Set Daily Report

POST http://localhost:3000/analytics/daily HTTP/1.1
content-type: application/json

{}