#################################################################################################
### This requests use REST Client                                                             ###
### Install Componente: https://marketplace.visualstudio.com/items?itemName=humao.rest-client ###
#################################################################################################

@email = "felipe.wget@gmail.com"
@password = "123456"
@application = ""

### Create Auth

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "password": "asdsadsadsadsaas",
    "application": "rede"
}

### Login

POST http://localhost:3000/auth HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "password": "123456",
    "application": "rede"
}

### Update Password

PATCH http://localhost:3000/auth/change-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "password": "asdsadsadsadsaas",
    "application": "",
    "new-password": ""
}

### Remove Auth

DELETE http://localhost:3000/auth HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "password": "asdsadsadsadsaas",
    "application": "rede"
}