#################################################################################################
### This requests use REST Client                                                             ###
### Install Componente: https://marketplace.visualstudio.com/items?itemName=humao.rest-client ###
#################################################################################################

### Send recovery Token

POST http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wget@gmail.com"
}

### Check Recovery Token

GET http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "recovery-token": "{Token}"
}

### Remove all expired recovery tokens

DELETE http://localhost:3000/recover-password/all HTTP/1.1
content-type: application/json

{}

### Update password by recovery token

PATCH http://localhost:3000/recover-password/update-password HTTP/1.1
content-type: application/json

{
    "recovery-token": "{Token}",
    "new-password": ""
}