#################################################################################################
### This requests use REST Client                                                             ###
### Install Componente: https://marketplace.visualstudio.com/items?itemName=humao.rest-client ###
#################################################################################################

### Send recovery Token

POST http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wget@gmail.com",
    "application": ""
}

### Check Recovery Token

GET http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wget@gmail.com",
    "token": "83c46fc0b7849ec67c026e1c7060f5ea78c41c778a5062f397e56315865ee5090af3030af7f829d64b04261f9bd8bd86d8a40ee4cea9c9976bd7cf5ceba71287",
    "application": ""
}

### Remove all expired recovery tokens

DELETE http://localhost:3000/recover-password/all HTTP/1.1
content-type: application/json

{}

### Update password by recovery token

PATCH http://localhost:3000/recover-password/update-password HTTP/1.1
content-type: application/json

{
    "token": "015fbebe979b560d7154619ec10575064ccb47dbf1a1e97eb50a6ddd03d49107c08b928a0f8d288b94fb01220d04da1dcc2c89d901b971a9ec485667145e8217",
    "email": "felipe.wget@gmail.com",
    "application": "",
    "new_password": "123456"
}