#################################################################################################
### This requests use REST Client                                                             ###
### Install Componente: https://marketplace.visualstudio.com/items?itemName=humao.rest-client ###
#################################################################################################

### Send recovery Token

POST http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "application": "rede"
}

### Check Recovery Token

GET http://localhost:3000/recover-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "token": "be9e8f6b5d98dcb4a62d822ab182816c88a9fd18cacdc29448cf5ead06f2ef1a44733000b21b3abecf1acd3592fc8a334569fc21cfce897d9d2fc4260c3feef8",
    "application": "rede"
}

### Remove all expired recovery tokens

DELETE http://localhost:3000/recover-password/all HTTP/1.1
content-type: application/json

{}

### Update password by recovery token

PATCH http://localhost:3000/recover-password/update-password HTTP/1.1
content-type: application/json

{
    "email": "felipe.wgxxet@gmail.com",
    "token": "be9e8f6b5d98dcb4a62d822ab182816c88a9fd18cacdc29448cf5ead06f2ef1a44733000b21b3abecf1acd3592fc8a334569fc21cfce897d9d2fc4260c3feef8",
    "application": "rede",
    "new_password": "123456"
}